version: '3.7'

networks: 
  backend-test:

services:
  
  app1:
    image: app1:$BUILD_ID
    container_name: app1-test
    networks: 
      - backend-test
    restart: always

  app2:
    image: app2:$BUILD_ID
    container_name: app2-test
    networks: 
      - backend-test
    restart: always
  
  lb:
    image: lb:$BUILD_ID
    container_name: lb-test
    depends_on:
      - app1
      - app2
    ports:
      - '8081:8081'
    networks: 
      - backend-test
    restart: always
