version: '3.7'

networks: 
  backend-prod:

services: 

  app1:
    image: app1:$BUILD_ID
    container_name: app1-prod
    networks: 
      - backend-prod
    restart: always

  app2:
    image: app2:$BUILD_ID
    container_name: app2-prod
    networks: 
      - backend-prod
    restart: always
    
  lb:
    image: lb:$BUILD_ID
    container_name: lb-prod
    depends_on:
      - app1
      - app2
    ports:
      - '80:8081'
    networks: 
      - backend-prod
    restart: always
